import { CheckCircle2, ChevronDown, Pencil, RefreshCcw, Search, Send, UserRoundCheck } from 'lucide-react'
import { type FormEvent, useEffect, useMemo, useState } from 'react'
import { DashboardHeader } from '../../../components/DashboardHeader'
import { apiFetch } from '../../../lib/api'
import '../operations.css'

type EventRow={id:number;event_type:string;from_status?:string|null;to_status:string;comments?:string|null;actor_name?:string|null;actor_role?:string|null;created_at:string}
type PM={id:number;full_name:string;email:string;employee_id?:string|null}
type Project={
  id:number;client_id:number;project_code:string;project_name:string;client_code?:string|null;client_name?:string|null;start_date?:string|null;end_date?:string|null;
  description?:string|null;scope_text?:string|null;quantity?:number|null;quantity_unit?:string|null;priority?:string|null;commercial_value?:number|null;currency?:string|null;
  po_wo_number?:string|null;attachment_references?:string[];workflow_status:string;finance_feedback?:string|null;project_manager_id?:number|null;project_manager_name?:string|null;
  submission_count?:number;finance_reviewer_name?:string|null;finance_reviewed_at?:string|null;events?:EventRow[]
}
type Dashboard={projects:Project[];project_managers:PM[]}
type Form={client_id:number;project_code:string;project_name:string;start_date:string;end_date:string;scope_text:string;quantity:string;quantity_unit:string;priority:string;commercial_value:string;currency:string;po_wo_number:string;description:string;attachment_references:string}
function label(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function financeBucket(status:string){if(status==='draft')return'draft';if(status==='pending_finance_approval')return'pending';if(status==='finance_returned')return'returned';return'approved'}
function operationalBucket(status:string){if(status==='closed')return'closed';if(status==='finance_closure_pending')return'closure';if(['pm_assigned','team_assigned','in_progress'].includes(status))return'active';return'not_started'}

export function BDProjectManagementPage(){
  const [data,setData]=useState<Dashboard|null>(null);const [query,setQuery]=useState('');const [financeFilter,setFinanceFilter]=useState('all');const [operationalFilter,setOperationalFilter]=useState('all')
  const [selectedId,setSelectedId]=useState<number|null>(null);const [editing,setEditing]=useState<Form|null>(null);const [pmChoice,setPmChoice]=useState<Record<number,string>>({})
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('')
  function load(){setError('');void apiFetch<Dashboard>('/operations/workflow/bd/dashboard').then(setData).catch(err=>setError(err instanceof Error?err.message:'Unable to load projects'))}
  useEffect(load,[])
  const rows=useMemo(()=>{const needle=query.trim().toLowerCase();return(data?.projects??[]).filter(row=>(!needle||row.project_code.toLowerCase().includes(needle)||(row.client_code||'').toLowerCase().includes(needle))&&(financeFilter==='all'||financeBucket(row.workflow_status)===financeFilter)&&(operationalFilter==='all'||operationalBucket(row.workflow_status)===operationalFilter))},[data,query,financeFilter,operationalFilter])
  const selected=data?.projects.find(row=>row.id===selectedId)??null
  function startEdit(row:Project){setSelectedId(row.id);setEditing({client_id:row.client_id,project_code:row.project_code,project_name:row.project_name,start_date:row.start_date||'',end_date:row.end_date||'',scope_text:row.scope_text||'',quantity:row.quantity==null?'':String(row.quantity),quantity_unit:row.quantity_unit||'unit',priority:row.priority||'medium',commercial_value:row.commercial_value==null?'':String(row.commercial_value),currency:row.currency||'INR',po_wo_number:row.po_wo_number||'',description:row.description||'',attachment_references:(row.attachment_references||[]).join('\n')})}
  async function saveEdit(event:FormEvent){event.preventDefault();if(!selected||!editing)return;setBusy(true);setError('');try{await apiFetch(`/operations/workflow/bd/projects/${selected.id}`,{method:'PUT',body:JSON.stringify({...editing,quantity:editing.quantity===''?null:Number(editing.quantity),commercial_value:editing.commercial_value===''?null:Number(editing.commercial_value),po_wo_number:editing.po_wo_number||null,description:editing.description||null,attachment_references:editing.attachment_references.split('\n').map(value=>value.trim()).filter(Boolean)})});setNotice(`${selected.project_code} updated without creating a duplicate.`);setEditing(null);load()}catch(err){setError(err instanceof Error?err.message:'Unable to update project')}finally{setBusy(false)}}
  async function submit(row:Project){if(!window.confirm(`Submit ${row.project_code} to Finance?`))return;setBusy(true);setError('');try{await apiFetch(`/operations/workflow/bd/projects/${row.id}/submit-finance`,{method:'POST'});setNotice(`${row.project_code} submitted to Finance.`);load()}catch(err){setError(err instanceof Error?err.message:'Unable to submit project')}finally{setBusy(false)}}
  async function assignPm(row:Project){const value=pmChoice[row.id]??(row.project_manager_id?String(row.project_manager_id):'');if(!value){setError('Select exactly one Ortho Project Manager.');return}setBusy(true);setError('');try{await apiFetch(`/operations/workflow/bd/projects/${row.id}/assign-pm`,{method:'POST',body:JSON.stringify({project_manager_id:Number(value)})});setNotice(`${row.project_code}: Project Manager assigned.`);load()}catch(err){setError(err instanceof Error?err.message:'Unable to assign Project Manager')}finally{setBusy(false)}}

  return <div className="operations-page">
    <DashboardHeader eyebrow="BUSINESS DEVELOPMENT" title="Project Management" description="Search the complete project register, review history, correct returned projects, resubmit the same record, and assign a PM only after Finance approval." actions={<button className="operations-button secondary" onClick={load}><RefreshCcw size={16}/> Refresh</button>}/>
    {notice&&<div className="operations-alert success">{notice}</div>}{error&&<div className="operations-alert error">{error}</div>}
    <section className="operations-panel"><div className="operations-filter-grid"><label className="operations-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Project ID / Client ID"/></label><label className="operations-field"><span>Finance Status</span><select value={financeFilter} onChange={e=>setFinanceFilter(e.target.value)}><option value="all">All</option><option value="draft">Draft</option><option value="pending">Pending Finance</option><option value="returned">Returned</option><option value="approved">Approved</option></select></label><label className="operations-field"><span>Operational Status</span><select value={operationalFilter} onChange={e=>setOperationalFilter(e.target.value)}><option value="all">All</option><option value="not_started">Not Started</option><option value="active">Active</option><option value="closure">Closure Pending</option><option value="closed">Closed</option></select></label></div>
      <div className="operations-table-wrap"><table className="operations-table"><thead><tr><th>Project / Client</th><th>Finance Status</th><th>Operational Status</th><th>Project Manager</th><th>Actions</th></tr></thead><tbody>{rows.map(row=>{const editable=['draft','finance_returned'].includes(row.workflow_status);const canAssign=['finance_approved','pm_assigned'].includes(row.workflow_status);return <tr key={row.id}><td><button className="operations-row-link" onClick={()=>{setSelectedId(row.id);setEditing(null)}}><strong>{row.project_code}</strong><small>{row.client_code} · {row.project_name}</small></button></td><td><span className={`operations-status ${row.workflow_status==='finance_returned'?'danger':'warning'}`}>{label(row.workflow_status)}</span></td><td>{label(operationalBucket(row.workflow_status))}</td><td>{canAssign?<div className="operations-actions"><select value={pmChoice[row.id]??(row.project_manager_id?String(row.project_manager_id):'')} onChange={e=>setPmChoice({...pmChoice,[row.id]:e.target.value})}><option value="">Select Ortho PM</option>{data?.project_managers.map(pm=><option key={pm.id} value={pm.id}>{pm.employee_id?`${pm.employee_id} · `:''}{pm.full_name}</option>)}</select><button className="operations-button secondary" disabled={busy} onClick={()=>void assignPm(row)}><UserRoundCheck size={14}/> Assign</button></div>:row.project_manager_name||'Not assigned'}</td><td><div className="operations-actions"><button className="operations-button secondary" onClick={()=>{setSelectedId(row.id);setEditing(null)}}><ChevronDown size={14}/> Details</button>{editable&&<button className="operations-button secondary" onClick={()=>startEdit(row)}><Pencil size={14}/> Edit</button>}{editable&&<button className="operations-button" disabled={busy} onClick={()=>void submit(row)}><Send size={14}/> Submit</button>}</div></td></tr>})}{!rows.length&&<tr><td colSpan={5}><div className="operations-empty">No projects match these filters.</div></td></tr>}</tbody></table></div>
    </section>

    {selected&&<section className="operations-panel"><header><div><span className="operations-kicker">{selected.client_code} · {selected.project_code}</span><h2>{selected.project_name}</h2><p>{selected.start_date||'—'} → {selected.end_date||'—'}</p></div><span className="operations-status">{label(selected.workflow_status)}</span></header>
      <div className="operations-detail-grid"><div><span>Project Scope</span><strong>{selected.scope_text||'—'}</strong></div><div><span>Commercial</span><strong>{selected.currency||'INR'} {selected.commercial_value?.toLocaleString('en-IN')||'—'}</strong></div><div><span>PO / WO</span><strong>{selected.po_wo_number||'—'}</strong></div><div><span>Attachments</span><strong>{selected.attachment_references?.join(', ')||'None recorded'}</strong></div><div><span>Finance Reviewer</span><strong>{selected.finance_reviewer_name||'Not reviewed'} {selected.finance_reviewed_at?`· ${new Date(selected.finance_reviewed_at).toLocaleString('en-IN')}`:''}</strong></div><div><span>Submission Count</span><strong>{selected.submission_count||0}</strong></div></div>
      {selected.finance_feedback&&<div className="operations-alert error"><b>Finance feedback:</b> {selected.finance_feedback}</div>}
      <div className="operations-activity-list">{(selected.events??[]).slice().reverse().map(event=><div key={event.id}><CheckCircle2 size={15}/><div><strong>{label(event.event_type)} · {event.actor_name||'System'}</strong><span>{new Date(event.created_at).toLocaleString('en-IN')} · {label(event.to_status)}</span>{event.comments&&<small>{event.comments}</small>}</div></div>)}</div>
    </section>}

    {selected&&editing&&<section className="operations-panel"><header><div><span className="operations-kicker">EDIT SAME PROJECT RECORD</span><h2>{selected.project_code}</h2><p>Available only for Draft or Finance Returned projects.</p></div></header><form className="operations-form-grid" onSubmit={saveEdit}>
      <label className="operations-field"><span>Project ID *</span><input required value={editing.project_code} onChange={e=>setEditing({...editing,project_code:e.target.value.toUpperCase()})}/></label><label className="operations-field"><span>Project Name *</span><input required value={editing.project_name} onChange={e=>setEditing({...editing,project_name:e.target.value})}/></label>
      <label className="operations-field"><span>Start Date *</span><input required type="date" value={editing.start_date} onChange={e=>setEditing({...editing,start_date:e.target.value})}/></label><label className="operations-field"><span>End Date *</span><input required type="date" min={editing.start_date||undefined} value={editing.end_date} onChange={e=>setEditing({...editing,end_date:e.target.value})}/></label>
      <label className="operations-field operations-span-2"><span>Project Scope *</span><textarea required value={editing.scope_text} onChange={e=>setEditing({...editing,scope_text:e.target.value})}/></label><label className="operations-field"><span>Project Value</span><input type="number" min="0" value={editing.commercial_value} onChange={e=>setEditing({...editing,commercial_value:e.target.value})}/></label><label className="operations-field"><span>Currency</span><input value={editing.currency} onChange={e=>setEditing({...editing,currency:e.target.value})}/></label><label className="operations-field"><span>PO / WO</span><input value={editing.po_wo_number} onChange={e=>setEditing({...editing,po_wo_number:e.target.value})}/></label><label className="operations-field"><span>Attachments / References</span><textarea value={editing.attachment_references} onChange={e=>setEditing({...editing,attachment_references:e.target.value})}/></label><label className="operations-field operations-span-2"><span>Remarks</span><textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="operations-actions operations-span-2"><button className="operations-button" disabled={busy}>Save Corrections</button><button type="button" className="operations-button secondary" onClick={()=>setEditing(null)}>Cancel</button></div>
    </form></section>}
  </div>
}
